#!/bin/bash
# Update server
apt-get update && apt-get upgrade -y

#Install MongoDB
sudo apt-get install -y mongodb

# Get a node version from nvm
nvm install v5.10.1

# Install nodemon (for monitoring file changes during development)
npm install -g nodemon

# Install all packages for this project
npm install --save
